---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: false

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      privileged: true
      pid_one_command: /bin/systemd
      intermediate_instructions:
      - RUN /usr/bin/apt-get update && /usr/bin/apt-get install -y apt-transport-https net-tools && rm -r /var/cache/apt /var/lib/apt/lists
  - name: centos-7
    driver:
      image: centos:7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
      - RUN yum install -y net-tools

suites:
  - name: default
    run_list:
      - recipe[traefik::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
