name 'traefik'
maintainer 'sous-chefs'
maintainer_email 'help@sous-chefs.org'
license      'Apache-2.0'
description  'Installs/Configures traefik'
version      '0.2.0'
chef_version '>= 15.3'

issues_url 'https://github.com/redguide/traefik/issues'
source_url 'https://github.com/redguide/traefik'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'oracle'
supports 'scientific'
supports 'amazon'

gem 'toml-rb', '~> 1.0.0'
depends 'systemd', '~> 2.1.3'
